# Generated by Django 2.1.2 on 2018-10-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='dishes',
            field=models.ManyToManyField(blank=True, null=True, to='app.Dish'),
        ),
    ]
