# Generated by Django 2.1.2 on 2018-10-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181031_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingridients',
            field=models.ManyToManyField(blank=True, to='app.Ingridient'),
        ),
    ]
