# Generated by Django 2.1.2 on 2018-10-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181031_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='reserve_datetime',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
