# Generated by Django 2.1.2 on 2018-10-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_table_reserve_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='reserve_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
