# Generated by Django 2.1.2 on 2018-11-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181031_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingridient',
            name='calorie',
        ),
        migrations.AddField(
            model_name='dish',
            name='calorie',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='type',
            field=models.CharField(choices=[('drink', 'Напиток'), ('warm', 'Горячее блюдо'), ('dessert', 'Десерт'), ('-', '-'), ('', ''), ('', '')], default='-', max_length=30),
        ),
    ]
