# Generated by Django 2.1.2 on 2018-11-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181101_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='add_ingridients',
            field=models.ManyToManyField(blank='True', related_name='add_ingridients', to='app.Ingridient'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='type',
            field=models.CharField(choices=[('drink', 'Напиток'), ('warm', 'Горячее блюдо'), ('dessert', 'Десерт'), ('-', '-'), ('zakus', 'Закуска'), ('soup', 'Суп'), ('salad', 'Салат'), ('main', 'Основное блюдо'), ('garn', 'Гарнир'), ('vipechka', 'Выпечка'), ('cons', 'Консервирование'), ('sous', 'Соус'), ('hookah', 'Кальян')], default='-', max_length=30),
        ),
    ]
