# Generated by Django 2.1.2 on 2018-11-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181102_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='add_ingridients',
        ),
        migrations.AddField(
            model_name='table',
            name='add_ingridients',
            field=models.ManyToManyField(blank='True', to='app.Ingridient'),
        ),
    ]
