# Generated by Django 2.1.2 on 2018-11-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181102_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='add_ingridients',
        ),
        migrations.AddField(
            model_name='dish',
            name='add_ingridients',
            field=models.ManyToManyField(blank=True, related_name='add_ingridients', to='app.Ingridient'),
        ),
    ]
